name: Coverage

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/**"

  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      - name: Install Dependencies
        run: flutter packages get
      - name: Format
        run: flutter format --set-exit-if-changed lib test
      - name: Analyze
        run: flutter analyze lib test
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          min_coverage: 80
          # path: "./coverage/lcov.info"
          # exclude: "**/*_observer.dart **/change.dart"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          # directory: ./coverage/
          # env_vars: OS,PYTHON
          # fail_ci_if_error: true
          files: ./lcov.info
          # flags: unittests
          # name: codecov-umbrella
          # path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
