name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with main channel
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: main
      - run: flutter doctor -v

      # Checkout gallery code and get packages.
      - name: Checkout gallery code
        uses: actions/checkout@v2
      - run: flutter pub get

      # Analyze, check formatting, and run unit tests.
      - run: flutter analyze
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .
      - name: Run Flutter unit tests
        run: flutter test
